
# 1. Why Seq2Seq fails on long sentences

A basic Seq2Seq model encodes the entire input sentence into a **single fixed-length context vector**. For long sentences, this vector cannot store all the important information, so some details are lost. As a result, the decoder receives incomplete information, leading to poor translations.

**One-line answer for interviews:**

> Seq2Seq struggles with long sentences because it compresses the entire input into one fixed-size context vector, creating an information bottleneck.

---

# 2. Context Vector Bottleneck

The **Context Vector Bottleneck** is the limitation of a basic Seq2Seq model where all the information from the input sentence must fit into a single vector before being passed to the decoder.

As sentence length increases:

* More information must be stored.
* Important details may be forgotten.
* Translation quality decreases.

Example:

```text
Long Sentence
      ↓
One Fixed Context Vector
      ↓
Some information is lost
      ↓
Poor Translation
```

---

# 3. Why Attention was invented

Attention was invented to overcome the **context vector bottleneck**.

Instead of forcing the decoder to rely on only one context vector, Attention allows it to **look at all encoder outputs** and focus on the most relevant words while generating each output word.

**One-line answer:**

> Attention lets the decoder access all encoder outputs instead of only the final hidden state.

---

# 4. How Attention solves the problem

Attention computes a relevance score between the decoder's current hidden state and every encoder output.

The steps are:

1. Compare the decoder hidden state with each encoder output.
2. Compute attention scores.
3. Apply Softmax to obtain attention weights.
4. Compute a weighted sum of all encoder outputs.
5. Use this weighted context vector to generate the next word.

This allows the decoder to focus on the most relevant parts of the input sentence.

Example:

```text
Encoder Outputs

h1  h2  h3  h4

↓

Attention Scores

↓

Softmax

↓

Attention Weights

↓

Weighted Sum

↓

New Context Vector

↓

Decoder
```

---

# 5. Real-life analogy

Imagine you're answering questions from a textbook.

Without Attention:

You close the book and try to answer everything from memory.

With Attention:

You keep the book open and look at the relevant page whenever you answer a question.

Similarly, the decoder doesn't rely only on memory—it looks back at the relevant encoder outputs whenever it generates a word.

---

# 6. What is the Context Vector?

In a basic Seq2Seq model, the **context vector** is the encoder's final hidden state that summarizes the entire input sentence.

In an Attention-based model, the context vector is **not** just the final hidden state. It is a **weighted sum of all encoder outputs**, where more relevant words receive higher attention weights.

---

# 7. Why does translation quality decrease for long sentences?

Translation quality decreases because the encoder must compress all the information from a long sentence into one fixed-length vector.

As the sentence becomes longer:

* Earlier information may be forgotten.
* Important relationships between words are lost.
* The decoder receives an incomplete representation of the input.

---

# 8. How does Attention solve this?

Attention allows the decoder to look back at **all encoder outputs** instead of relying on a single context vector.

For each output word, it computes attention scores, identifies the most relevant input words, and creates a new context vector focused on those words.

This greatly improves translation, especially for long sentences.

---

# 9. Does the decoder use only the final hidden state after Attention?

**No.**

In a basic Seq2Seq model, the decoder uses only the encoder's final hidden state (context vector).

In an Attention-based model, the decoder uses:

* Its current hidden state.
* All encoder outputs.
* The attention-generated context vector (weighted sum of encoder outputs).

So, it is **not limited to only the final hidden state**.

---

# 10. What information does the decoder receive in an Attention-based model?

The decoder receives:

* **All encoder outputs** (hidden states for every input token).
* **Its previous hidden state.**
* **The attention-generated context vector** (weighted combination of encoder outputs).
* **The previous output token** (or the ground-truth token during training with teacher forcing).

These together help it generate the next word accurately.

---

## Quick Revision Table

| Question                                  | Short Answer                                                                          |
| ----------------------------------------- | ------------------------------------------------------------------------------------- |
| Why Seq2Seq fails?                        | Entire sentence is compressed into one fixed context vector.                          |
| Context Vector Bottleneck?                | A single vector cannot store all information from long sentences.                     |
| Why Attention?                            | To let the decoder access all encoder outputs instead of one vector.                  |
| How Attention works?                      | Scores → Softmax → Weights → Weighted sum → New context vector.                       |
| Real-life analogy?                        | Answering questions with the book open instead of relying only on memory.             |
| Context Vector?                           | Basic Seq2Seq: final hidden state. Attention: weighted sum of all encoder outputs.    |
| Why translation quality decreases?        | Long sentences cause information loss in the fixed context vector.                    |
| How does Attention solve it?              | It dynamically focuses on the most relevant input words.                              |
| Does decoder use only final hidden state? | No. It uses all encoder outputs through Attention.                                    |
| What does decoder receive?                | Encoder outputs, previous hidden state, attention context vector, and previous token. |

If you can explain these 10 answers in your own words, you'll have a solid conceptual understanding before moving on to implementing the Attention mechanism in code.


In [2]:
import torch

encoder_outputs= torch.tensor([
    [1.0, 2.0],
    [0.5, 1.5],
    [2.0, 1.0]
])

decoder_hidden = torch.tensor([1.0, 1.0])

scores = torch.matmul(
    encoder_outputs,
    decoder_hidden
)

print(scores)

tensor([3., 2., 3.])


In [3]:
weights = torch.softmax(scores, dim=0)

print(weights)

tensor([0.4223, 0.1554, 0.4223])


In [4]:
context = torch.sum(
    weights.unsqueeze(1) * encoder_outputs,
    dim=0
)

print(context)

tensor([1.3446, 1.5000])
